[package]
name = "rshima"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.6"
octocrab = "0.17.0"
poise = "0.4.1"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
