[package]
name = "rshima"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.6"
html2text = "0.4.4"
octocrab = "0.17.0"
poise = "0.5.0"
rand = "0.8.5"
tokio = { version = "1.22.0", features = ["full"] }
